stages:
- stage: Push_to_ACR
  displayName: Deploy To ACR
  jobs: 
  - job: stageing
    displayName: stageing
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/stageing')
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'sakcrsak.azurecr.io'
          repository: backend
          command: 'buildAndPush'
          Dockerfile: '**/api/Dockerfile'
          tags: |
            $(Build.BuildID)
            latest

      - task: CopyPublishBuildArtifacts@1
        inputs:
          Contents: '**'
          ArtifactName: 'drop'
          ArtifactType: 'Container'
          
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
  
  - job: dev
    displayName: dev
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'sakcrsak.azurecr.io'
          repository: backend_dev
          command: 'buildAndPush'
          Dockerfile: '**/api/Dockerfile'
          tags: 'dev'
<<<<<<< HEAD
          
=======

>>>>>>> dev
      - task: CopyPublishBuildArtifacts@1
        inputs:
          Contents: '**'
          ArtifactName: 'drop'
          ArtifactType: 'Container'
          
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

  - job: production
    displayName: production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/production')
    steps:
      - task: CopyPublishBuildArtifacts@1
        inputs:
          Contents: '**'
          ArtifactName: 'drop'
          ArtifactType: 'Container'
          
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
  
    

